# Generated by Django 2.2 on 2019-04-17 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='菜品名称')),
                ('category', models.IntegerField(choices=[(1, '主食'), (2, '配菜'), (3, '套餐'), (4, '饮品')], help_text='菜品类别', verbose_name='菜品类别')),
                ('desc', models.TextField(blank=True, max_length=50, null=True, verbose_name='菜品描述')),
                ('num', models.IntegerField(blank=True, help_text='菜品库存', null=True, verbose_name='菜品份数')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
            },
        ),
        migrations.CreateModel(
            name='Windows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='窗口名称')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='菜单')),
            ],
            options={
                'verbose_name': '食堂窗口',
                'verbose_name_plural': '食堂窗口',
            },
        ),
    ]
