# Generated by Django 2.0 on 2019-05-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexad',
            name='category',
        ),
        migrations.AddField(
            model_name='indexad',
            name='window',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='window', to='goods.Windows', verbose_name='商品类目'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='windows',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='goods.PlaceCategory', verbose_name='窗口类目'),
        ),
    ]
