# Generated by Django 2.0 on 2019-05-03 21:45

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190428_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], help_text='食堂', verbose_name='食堂')),
                ('code', models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code')),
                ('is_tab', models.BooleanField(default=False, help_text='是否导航', verbose_name='是否导航')),
                ('desc', DjangoUeditor.models.UEditorField(default='', verbose_name='类别描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='goods.PlaceCategory', verbose_name='父类目级别')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'verbose_name': '类别', 'verbose_name_plural': '类别'},
        ),
        migrations.AddField(
            model_name='goods',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='是否热销'),
        ),
        migrations.AddField(
            model_name='goods',
            name='ship_free',
            field=models.BooleanField(default=True, verbose_name='是否承担运费'),
        ),
        migrations.AddField(
            model_name='goodscategory',
            name='image',
            field=models.ImageField(default='', max_length=200, upload_to='kinds/'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='desc',
            field=models.TextField(default='', help_text='类别描述', max_length=200, verbose_name='类别描述'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='name',
            field=models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名'),
        ),
        migrations.AlterField(
            model_name='indexad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='goods.PlaceCategory', verbose_name='商品类目'),
        ),
        migrations.AlterField(
            model_name='windows',
            name='windows_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='windows/', verbose_name='窗口图'),
        ),
        migrations.AlterModelTable(
            name='goodscategory',
            table='goods_goodscategory',
        ),
        migrations.AddField(
            model_name='goodscategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goodscategory', to='goods.PlaceCategory', verbose_name='商品类别'),
        ),
    ]
