# Generated by Django 2.0 on 2019-05-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190521_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='windows',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
