# Generated by Django 2.0 on 2019-05-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190503_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='placecategory',
            name='category_type',
            field=models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], default='1', help_text='类目级别', verbose_name='类目级别'),
        ),
        migrations.AlterField(
            model_name='placecategory',
            name='name',
            field=models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名'),
        ),
    ]
