# Generated by Django 2.0 on 2019-05-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190503_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placecategory',
            options={'verbose_name': '食堂类别', 'verbose_name_plural': '食堂类别'},
        ),
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='价格'),
        ),
        migrations.AddField(
            model_name='windows',
            name='windows_desc',
            field=models.TextField(default='', help_text='类别描述', max_length=200, verbose_name='类别描述'),
        ),
    ]
