# Generated by Django 2.0 on 2019-05-07 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20190505_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windows',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='goods.PlaceCategory', verbose_name='窗口类目'),
        ),
    ]
