# Generated by Django 2.0 on 2019-05-07 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20190507_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placecategory',
            old_name='parent_category',
            new_name='place_category',
        ),
        migrations.AlterField(
            model_name='windows',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='goods.GoodsCategory', verbose_name='窗口类目'),
        ),
    ]
