# Generated by Django 2.0 on 2019-05-07 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20190507_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodscategory',
            name='category',
        ),
        migrations.AlterField(
            model_name='windows',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='goods.PlaceCategory', verbose_name='窗口类目'),
        ),
        migrations.DeleteModel(
            name='GoodsCategory',
        ),
    ]
