# Generated by Django 2.0 on 2019-05-12 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_goods_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='window',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
