# Generated by Django 2.2 on 2019-04-17 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20190417_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odergoods',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 17, 20, 25, 53, 812668), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 17, 20, 25, 53, 811667), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 17, 20, 25, 53, 811667), verbose_name='添加时间'),
        ),
    ]
