# Generated by Django 2.0 on 2019-05-19 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20190517_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='windows',
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 5, 19, 15, 33, 23, 702471), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 5, 19, 15, 33, 23, 702471), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 5, 19, 15, 33, 23, 702471), verbose_name='添加时间'),
        ),
    ]
