# Generated by Django 2.2 on 2019-04-18 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20190418_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odergoods',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 18, 14, 57, 52, 216786), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 18, 14, 57, 52, 215798), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 18, 14, 57, 52, 215798), verbose_name='添加时间'),
        ),
    ]
