# Generated by Django 2.0 on 2019-05-20 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20190519_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='signer_identity',
            field=models.CharField(default=221500102, max_length=9, verbose_name='签收人身份'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 5, 20, 15, 0, 18, 932705), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 5, 20, 15, 0, 18, 932705), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 5, 20, 15, 0, 18, 932705), verbose_name='添加时间'),
        ),
    ]
