# Generated by Django 2.0 on 2019-05-22 21:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190521_1610'),
        ('trade', '0011_auto_20190521_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='windows',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='goods.Windows', verbose_name='窗口'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 5, 22, 21, 45, 51, 522241), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 5, 22, 21, 45, 51, 522241), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 5, 22, 21, 45, 51, 522241), verbose_name='添加时间'),
        ),
    ]
