# Generated by Django 2.0 on 2019-04-30 20:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190428_1139'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_option', '0006_auto_20190429_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoodsFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime(2019, 4, 30, 20, 46, 9, 984302), verbose_name='添加时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏商品',
                'verbose_name_plural': '用户收藏商品',
            },
        ),
        migrations.CreateModel(
            name='UserWindowsFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime(2019, 4, 30, 20, 46, 9, 984302), verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('windows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Windows', verbose_name='窗口')),
            ],
            options={
                'verbose_name': '用户收藏窗口',
                'verbose_name_plural': '用户收藏窗口',
            },
        ),
        migrations.RemoveField(
            model_name='userfav',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='userfav',
            name='user',
        ),
        migrations.AlterField(
            model_name='leavingmessage',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 30, 20, 46, 9, 984302), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 30, 20, 46, 9, 984302), verbose_name='添加时间'),
        ),
        migrations.DeleteModel(
            name='UserFav',
        ),
    ]
