# Generated by Django 2.0 on 2019-05-20 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_option', '0007_auto_20190520_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='signer_identity',
            field=models.CharField(default=221500102, max_length=9, verbose_name='签收人身份'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leavingmessage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 20, 15, 13, 39, 275712), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 20, 15, 13, 39, 275712), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='usergoodsfav',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 5, 20, 15, 13, 39, 275712), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userwindowsfav',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 5, 20, 15, 13, 39, 275712), verbose_name='添加时间'),
        ),
    ]
