# Generated by Django 2.0 on 2019-04-30 21:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190428_1139'),
        ('user_option', '0007_auto_20190430_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavingmessage',
            name='windows',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='goods.Windows', verbose_name='窗口'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leavingmessage',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 30, 21, 38, 20, 783081), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 30, 21, 38, 20, 798706), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='usergoodsfav',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 30, 21, 38, 20, 783081), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userwindowsfav',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 30, 21, 38, 20, 783081), verbose_name='添加时间'),
        ),
    ]
