# Generated by Django 2.2 on 2019-04-18 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_option', '0007_auto_20190418_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavingmessage',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 18, 15, 14, 26, 787640), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 18, 15, 14, 26, 788640), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userfav',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 18, 15, 14, 26, 787640), verbose_name='添加时间'),
        ),
    ]
