# Generated by Django 2.0 on 2019-04-30 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_option', '0008_auto_20190430_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavingmessage',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 30, 21, 42, 52, 562520), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='leavingmessage',
            name='msg_type',
            field=models.CharField(choices=[('1', '留言'), ('2', '投诉'), ('3', '询问'), ('4', '售后'), ('5', '求购')], default='1', help_text='留言类型1(留言),2(投诉),3,(询问),4(售后),5(求购)', max_length=2, verbose_name='留言类型'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 30, 21, 42, 52, 562520), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='usergoodsfav',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 30, 21, 42, 52, 562520), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userwindowsfav',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 30, 21, 42, 52, 562520), verbose_name='添加时间'),
        ),
    ]
