# Generated by Django 2.0 on 2019-05-11 17:04

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0009_goods_is_new'),
        ('user_option', '0040_auto_20190511_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavingmessage',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 5, 11, 17, 4, 39, 312669), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 5, 11, 17, 4, 39, 312669), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='usergoodsfav',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 5, 11, 17, 4, 39, 312669), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userwindowsfav',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2019, 5, 11, 17, 4, 39, 312669), verbose_name='添加时间'),
        ),
        migrations.AlterUniqueTogether(
            name='usergoodsfav',
            unique_together={('user', 'goods')},
        ),
    ]
