# Generated by Django 2.0 on 2019-04-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifycode',
            options={'verbose_name': '密码', 'verbose_name_plural': '密码'},
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='mycode',
            field=models.CharField(max_length=10, verbose_name='密码'),
        ),
    ]
