# Generated by Django 2.0 on 2019-05-10 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mycode',
        ),
    ]
