# Generated by Django 2.2 on 2019-04-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='identity',
            new_name='identities',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='code',
            new_name='mycode',
        ),
        migrations.RenameField(
            model_name='verifycode',
            old_name='code',
            new_name='mycode',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
